[tool.poetry]
name = "pyriodicity"
version = "0.2.0rc0"
description = "An autocorrelation function-based seasonality periods automatic finder for univariate time series."

license = "MIT"
readme = ["README.md"]
repository = "https://github.com/iskandergaba/pyriodicity"

authors = ["Iskander Gaba <iskander@hey.com>"]
keywords = ["time", "series", "forecast", "analysis", "seasonality", "trend", "decomposition"]


[tool.poetry.dependencies]
python = "^3.10"
scipy = "^1.14.0"


[tool.poetry.group.test.dependencies]
pytest = "^7.4.3"
statsmodels = "^0.14.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
