[tool.poetry]
name = "auto-period-finder"
version = "0.0.10rc2"
description = "An autocorrelation function-based seasonality periods automatic finder for univariate time series."
authors = ["Iskander Gaba <iskander@hey.com>"]
repository = "https://github.com/iskandergaba/auto-period-finder"
readme = ["README.md", "LICENSE"]

[tool.poetry.dependencies]
python = "^3.10"
statsmodels = "^0.14.1"


[tool.poetry.group.test.dependencies]
pytest = "^7.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
