# This workflow will install uv, resolve the package dependencies, run tests, build
# and publish package versions to TestPyPI upon pushing tags of the format "*.*.*".

name: Publish to TestPyPI
on:
  push:
    tags:
      - "*.*.*"

jobs:
  TestPyPI-Release:
    name: Build and Publish to TestPyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ vars.PYTHON_LATEST_VERSION }}

      - name: Install dependencies
        run: uv sync

      - name: Run tests
        run: uv run pytest

      - name: Publish package to TestPyPI
        run: |
          uv build
          uv publish --publish-url https://test.pypi.org/legacy/
